### PR TITLE
Fix Memory leaks with ScopedWindsorServiceProvider

### LINKED ISSUE #26: Memory leaks with ScopedWindsorServiceProvider
Hi @hikalkan ,
I'm using abp v3.1.2 and asp.net zero v4.6.1. with .net framework 4.6.1 and asp.net core 2.0.
My application run with large memory(about 2G to 4G), I checked it with the memory profiler tool.
and I found the ScopedWindsorServiceProvider have a lot of instances and bytes(see the image).
image
what's worse, the ScopedWindsorServiceProvider held about 1G instances.

I check the code in this repository, I found the ScopedWindsorServiceProvider implement the IDisposable.but it seems no code invoke the windsor container's **Release** method to release it.

### PR DESCRIPTION
**Pull request by flexem**
Fixes #26

### CODE REVIEW

**Comment by hikalkan** [comment]
Thanks a lot. I will review and merge it.

**Comment by hikalkan** [comment]
You are totally right. Sorry for the bug and thank you very much for investigating and fixing it.

I also released serviceprovider inside servicescope: https://github.com/volosoft/castle-windsor-ms-adapter/commit/80ead0b609b73c9e9f7e44ec41d1c369fc7a78f4

**Comment by flexem** [comment]
The Windsor don't track the class which do not implement IDisposable interface.So may be do not need release it.Of cause,release it may be more better.

and You reminded me, I think release the GlobalScopedWindsorServiceProvider in it's Dispose method may be More necessary.
 https://github.com/volosoft/castle-windsor-ms-adapter/blob/80ead0b609b73c9e9f7e44ec41d1c369fc7a78f4/src/Castle.Windsor.MsDependencyInjection/GlobalScopedWindsorServiceProvider.cs#L14

**Comment by hikalkan** [comment]
Hi,

I just learned that "Windsor does not track the instance which do not implement IDisposable." I'm suprised, but it's reasonable.

However, we should not rely on that. If your non-disposable dependency depends on a disposable dependency, then castle tracks it (tested)! So, we should always release an object if resolved directly from contaier, because we can not know if the class will have a disposable dependency in the future.

**Comment by flexem** [comment]
Yes, You are right! How about "release the GlobalScopedWindsorServiceProvider in it's Dispose method"?

**Comment by hikalkan** [comment]
``OwnMsLifetimeScope.Dispose();`` in  ``GlobalScopedWindsorServiceProvider`` is correct.

**Comment by flexem** [comment]
I mean this:
```
using System;

namespace Castle.Windsor.MsDependencyInjection
{
    public class GlobalScopedWindsorServiceProvider : ScopedWindsorServiceProvider, IDisposable
    {
        private readonly IWindsorContainer _container;
        private bool _isDisposed;

        public GlobalScopedWindsorServiceProvider(IWindsorContainer container,
            MsLifetimeScopeProvider msLifetimeScopeProvider) : base(container, msLifetimeScopeProvider)
        {
            _container = container;
        }

        public void Dispose()
        {
            if (_isDisposed) return;
            OwnMsLifetimeScope.Dispose();
            _isDisposed = true;
            _container.Release(this);
        }
    }
}
```

**Comment by hikalkan** [comment]
Yes, it would be fine.

**Pull request merged**
